<?php
require_once __DIR__ . '/conn.php';
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/system_core.php';
require_login(array('admin', 'dorm'));

ensure_system_schema($conn);

$autoScanResult = run_alert_scan_job($conn, false);
if (is_array($autoScanResult) && isset($autoScanResult['skipped']) && !$autoScanResult['skipped']) {
    $autoGenerated = isset($autoScanResult['generated']) ? (int) $autoScanResult['generated'] : 0;
    write_operation_log($conn, '异常预警扫描', '自动扫描执行，生成或刷新预警 ' . $autoGenerated . ' 条');
}

if (isset($_GET['refresh']) && $_GET['refresh'] === '1') {
    $manualScanResult = run_alert_scan_job($conn, true);
    $generatedCount = isset($manualScanResult['generated']) ? (int) $manualScanResult['generated'] : 0;
    write_operation_log($conn, '异常预警扫描', '执行异常扫描，生成或刷新预警 ' . $generatedCount . ' 条');
    flash_set('success', '异常扫描完成，已生成或刷新 ' . $generatedCount . ' 条预警记录。');
    redirect_to('alerts.php');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = isset($_POST['action']) ? trim($_POST['action']) : '';
    if ($action === 'resolve') {
        $alertId = isset($_POST['alert_id']) ? (int) $_POST['alert_id'] : 0;
        if ($alertId > 0) {
            $resolvedBy = current_user_name();
            $updateStmt = $conn->prepare("UPDATE `alert_notifications` SET `status` = '已处理', `resolved_at` = NOW(), `resolved_by` = ? WHERE `alert_id` = ? LIMIT 1");
            if ($updateStmt) {
                $updateStmt->bind_param('si', $resolvedBy, $alertId);
                $updateStmt->execute();
                $updateStmt->close();
                write_operation_log($conn, '预警处理', '处理预警记录 ID：' . $alertId);
                flash_set('success', '预警记录已标记为已处理。');
            }
        }
        redirect_to('alerts.php');
    }
}

$keyword = isset($_GET['keyword']) ? trim($_GET['keyword']) : '';
$statusFilter = isset($_GET['status']) ? trim($_GET['status']) : '';
$typeFilter = isset($_GET['alert_type']) ? trim($_GET['alert_type']) : '';
$dateFrom = isset($_GET['date_from']) ? trim($_GET['date_from']) : '';
$dateTo = isset($_GET['date_to']) ? trim($_GET['date_to']) : '';
$page = isset($_GET['page']) ? (int) $_GET['page'] : 1;
if ($page < 1) {
    $page = 1;
}
$pageSize = 10;

$conditions = array();
if ($keyword !== '') {
    $keywordSafe = $conn->real_escape_string($keyword);
    $conditions[] = "(`student_id` LIKE '%{$keywordSafe}%' OR `student_name` LIKE '%{$keywordSafe}%' OR `message` LIKE '%{$keywordSafe}%')";
}
if ($statusFilter !== '') {
    $statusSafe = $conn->real_escape_string($statusFilter);
    $conditions[] = "`status` = '{$statusSafe}'";
}
if ($typeFilter !== '') {
    $typeSafe = $conn->real_escape_string($typeFilter);
    $conditions[] = "`alert_type` = '{$typeSafe}'";
}
if ($dateFrom !== '') {
    $dateFromSafe = $conn->real_escape_string($dateFrom);
    $conditions[] = "DATE(`created_at`) >= '{$dateFromSafe}'";
}
if ($dateTo !== '') {
    $dateToSafe = $conn->real_escape_string($dateTo);
    $conditions[] = "DATE(`created_at`) <= '{$dateToSafe}'";
}

$whereSql = empty($conditions) ? '' : 'WHERE ' . implode(' AND ', $conditions);
$countSql = "SELECT COUNT(*) AS total FROM `alert_notifications` {$whereSql}";
$countResult = $conn->query($countSql);
$total = 0;
if ($countResult && $row = $countResult->fetch_assoc()) {
    $total = (int) $row['total'];
}

$totalPages = (int) ceil($total / $pageSize);
if ($totalPages < 1) {
    $totalPages = 1;
}
if ($page > $totalPages) {
    $page = $totalPages;
}
$offset = ($page - 1) * $pageSize;

$listSql = "SELECT `alert_id`, `student_id`, `student_name`, `alert_type`, `alert_level`, `message`, `notify_channels`, `status`, `created_at`, `resolved_at`, `resolved_by`
FROM `alert_notifications`
{$whereSql}
ORDER BY `created_at` DESC, `alert_id` DESC
LIMIT {$offset}, {$pageSize}";
$listResult = $conn->query($listSql);

$summarySql = "SELECT 
    COUNT(*) AS total_count,
    SUM(CASE WHEN `status` = '待处理' THEN 1 ELSE 0 END) AS pending_count,
    SUM(CASE WHEN `alert_level` = '高' THEN 1 ELSE 0 END) AS high_count
FROM `alert_notifications`";
$summaryResult = $conn->query($summarySql);
$summaryData = array('total_count' => 0, 'pending_count' => 0, 'high_count' => 0);
if ($summaryResult && $row = $summaryResult->fetch_assoc()) {
    $summaryData = array(
        'total_count' => (int) $row['total_count'],
        'pending_count' => (int) $row['pending_count'],
        'high_count' => (int) $row['high_count']
    );
}

$successTip = flash_get('success');
$baseQuery = array(
    'keyword' => $keyword,
    'status' => $statusFilter,
    'alert_type' => $typeFilter,
    'date_from' => $dateFrom,
    'date_to' => $dateTo
);
$notifyChannels = system_setting($conn, 'alert_notify_channels', '系统消息,短信,邮件');
$autoScanEnabled = system_setting($conn, 'alert_auto_scan_enabled', '1');
$lastAlertScanDate = system_setting($conn, 'last_alert_scan_date', '');
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>异常预警</title>
    <link rel="stylesheet" href="css/app.css">
</head>
<body class="app-body">
<?php include __DIR__ . '/header.php'; ?>

<div class="page-wrap">
    <section class="panel">
        <h2>异常预警中心</h2>
        <div class="note">系统会根据连续未签到、频繁晚归和未归情况生成预警。当前通知渠道配置为：<?php echo h($notifyChannels); ?>。</div>
        <?php if ($successTip !== ''): ?>
            <div class="note"><?php echo h($successTip); ?></div>
        <?php endif; ?>
        <div class="note">
            自动日扫描：<?php echo $autoScanEnabled === '1' ? '已开启' : '已关闭'; ?>；
            最近扫描日期：<?php echo $lastAlertScanDate !== '' ? h($lastAlertScanDate) : '暂无'; ?>。
        </div>
        <div class="btn-row" style="margin-top:12px;">
            <a class="btn btn-primary" href="alerts.php?refresh=1">立即扫描异常</a>
            <?php if (is_admin_user()): ?>
                <a class="btn btn-muted" href="system.php">去调整预警阈值</a>
            <?php endif; ?>
        </div>
    </section>

    <section class="panel">
        <div class="stats-row">
            <div class="stat-card">
                <div class="stat-title">预警总数</div>
                <div class="stat-value"><?php echo (int) $summaryData['total_count']; ?></div>
            </div>
            <div class="stat-card">
                <div class="stat-title">待处理</div>
                <div class="stat-value"><?php echo (int) $summaryData['pending_count']; ?></div>
            </div>
            <div class="stat-card">
                <div class="stat-title">高等级预警</div>
                <div class="stat-value"><?php echo (int) $summaryData['high_count']; ?></div>
            </div>
        </div>
    </section>

    <section class="panel">
        <h3>筛选查询</h3>
        <form method="get" action="alerts.php" class="form-grid">
            <div class="field">
                <label for="keyword">学生 / 预警内容</label>
                <input id="keyword" name="keyword" value="<?php echo h($keyword); ?>" placeholder="姓名、学号或消息关键字">
            </div>
            <div class="field">
                <label for="alert_type">预警类型</label>
                <select id="alert_type" name="alert_type">
                    <option value="">全部类型</option>
                    <option value="连续未签到" <?php echo $typeFilter === '连续未签到' ? 'selected' : ''; ?>>连续未签到</option>
                    <option value="频繁晚归" <?php echo $typeFilter === '频繁晚归' ? 'selected' : ''; ?>>频繁晚归</option>
                    <option value="未归预警" <?php echo $typeFilter === '未归预警' ? 'selected' : ''; ?>>未归预警</option>
                    <option value="节后未返校" <?php echo $typeFilter === '节后未返校' ? 'selected' : ''; ?>>节后未返校</option>
                </select>
            </div>
            <div class="field">
                <label for="status">处理状态</label>
                <select id="status" name="status">
                    <option value="">全部状态</option>
                    <option value="待处理" <?php echo $statusFilter === '待处理' ? 'selected' : ''; ?>>待处理</option>
                    <option value="已处理" <?php echo $statusFilter === '已处理' ? 'selected' : ''; ?>>已处理</option>
                </select>
            </div>
            <div class="field">
                <label for="date_from">生成日期（起）</label>
                <input id="date_from" type="date" name="date_from" value="<?php echo h($dateFrom); ?>">
            </div>
            <div class="field">
                <label for="date_to">生成日期（止）</label>
                <input id="date_to" type="date" name="date_to" value="<?php echo h($dateTo); ?>">
            </div>
            <div class="btn-row">
                <button class="btn btn-primary" type="submit">筛选预警</button>
                <a class="btn btn-muted" href="alerts.php">重置条件</a>
            </div>
        </form>
    </section>

    <section class="panel">
        <h3>预警列表</h3>
        <table class="data-table">
            <thead>
            <tr>
                <th>ID</th>
                <th>学号</th>
                <th>姓名</th>
                <th>预警类型</th>
                <th>等级</th>
                <th>预警内容</th>
                <th>发送渠道</th>
                <th>状态</th>
                <th>生成时间</th>
                <th>处理信息</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <?php if ($listResult && $listResult->num_rows > 0): ?>
                <?php while ($row = $listResult->fetch_assoc()): ?>
                    <tr>
                        <td><?php echo (int) $row['alert_id']; ?></td>
                        <td><?php echo h($row['student_id']); ?></td>
                        <td><?php echo h($row['student_name']); ?></td>
                        <td><?php echo h($row['alert_type']); ?></td>
                        <td><span class="level-pill level-<?php echo $row['alert_level'] === '高' ? 'high' : 'mid'; ?>"><?php echo h($row['alert_level']); ?></span></td>
                        <td><?php echo h($row['message']); ?></td>
                        <td><?php echo h($row['notify_channels']); ?></td>
                        <td><span class="status-pill"><?php echo h($row['status']); ?></span></td>
                        <td><?php echo h($row['created_at']); ?></td>
                        <td>
                            <?php
                            if ($row['status'] === '已处理') {
                                echo h($row['resolved_by'] . ' / ' . $row['resolved_at']);
                            } else {
                                echo '待处理';
                            }
                            ?>
                        </td>
                        <td>
                            <?php if ($row['status'] !== '已处理'): ?>
                                <form method="post" action="alerts.php" style="display:inline-block;">
                                    <input type="hidden" name="action" value="resolve">
                                    <input type="hidden" name="alert_id" value="<?php echo (int) $row['alert_id']; ?>">
                                    <button class="link-button" type="submit" onclick="return confirm('确认将该预警标记为已处理吗？');">标记处理</button>
                                </form>
                            <?php else: ?>
                                已完成
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endwhile; ?>
            <?php else: ?>
                <tr>
                    <td colspan="11">暂无预警记录，请先执行异常扫描。</td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>

        <div class="pagination">
            <?php
            $firstQuery = $baseQuery;
            $firstQuery['page'] = 1;
            $prevQuery = $baseQuery;
            $prevQuery['page'] = max(1, $page - 1);
            $nextQuery = $baseQuery;
            $nextQuery['page'] = min($totalPages, $page + 1);
            $lastQuery = $baseQuery;
            $lastQuery['page'] = $totalPages;
            ?>
            <a href="alerts.php?<?php echo http_build_query($firstQuery); ?>">首页</a>
            <a href="alerts.php?<?php echo http_build_query($prevQuery); ?>">上一页</a>
            <span class="current"><?php echo (int) $page; ?></span>
            <a href="alerts.php?<?php echo http_build_query($nextQuery); ?>">下一页</a>
            <a href="alerts.php?<?php echo http_build_query($lastQuery); ?>">末页</a>
        </div>
    </section>
</div>
</body>
</html>
